### ISSUE TITLE
How to use this in a project

### ISSUE THREAD

**Issue by traviscrist** [Bang9/circleci-slack-approval#2]
Hello, this looks exactly like what I am looking for but I don't understand how you would pull this into an existing project with Circle CI. Can you explain how I would go about doing that? Thanks!

**Comment by bang9** [comment]
Hi, this project is a template using Express.
You can customize some settings and code of this project and use it as your server(app).

Please refer this [link](https://github.com/bang9/circleci-slack-approval#how-to-use-this-template)
